name: 'Google Chat Github Action'
description: 'Send a notification to Google Chat with the result of a GitHub Action'
author: 'JChrist'

inputs:
  name:
    description: 'Job Name'
    required: true
  url:
    description: 'Google Chat Webhook URL'
    required: true
  validationId:
    description: 'Salesforce Validation ID'
    required: true
  validationStatus
    description: 'Salesforce Validation Status'
    required: true
  validationUrl
    description: 'Salesforce Validation URL'
    required: true
  validationDetails
    description: 'Salesforce Validation Details'
    required: true

branding:
  icon: 'bell'
  color: 'green'

runs:
  using: node20
  main: dist/index.js
